# Generated by Django 3.2.7 on 2021-09-23 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_auto_20210921_0859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='time',
            field=models.DateField(),
        ),
    ]
