# Generated by Django 3.2.7 on 2021-09-23 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_alter_event_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='photoUrl',
            field=models.URLField(blank=True, max_length=300),
        ),
    ]
