# Generated by Django 3.2.7 on 2021-10-01 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0006_auto_20210927_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
